### PR TITLE
Add pipeline steps missing, remove staging and allow_skip

### PR DESCRIPTION
**Pull request by gadorcruz**
## What? 
add pipeline steps missing, remove staging and allow_skip
## Why? 
When promoting the uat env to production, it is found failing due to not being able to export the config repo.
## How? 
1. Add the following pipeline steps:
-sanity_check_build_prod and helpers
- clone_repos_prod
2. Removing staging from the code. 
3. Add a password condition for keycloak to skip only for uat and branch but required for production.
## Check list

- [x] I have reviewed my own pull request
- [ ] I have written tests (if relevant)

### CODE REVIEW

**Comment by adityababumallisettiHO** [comment]
@gadorcruz  Drone job is failing could be with some of the changes we have introduced. Can you please check

**Comment by adityababumallisettiHO** [comment]
@gadorcruz . Can we also remove these stg references from the repo please
https://github.com/search?q=repo%3AUKHomeOffice%2Fcoa%20stg&type=code

**Comment by gadorcruz** [comment]
As I said in slack, I was removing hof-config-services after this PR. It is done now.

**Comment by gadorcruz** [comment]
I fixed the lack of end of the password conditional. The deployment is working and the config files are now done.

**Comment by adityababumallisettiHO** [comment]
Good one! I am approving your PR.

**Review by adityababumallisettiHO — APPROVED** [review]
lgtm

**Review by dk4g — APPROVED** [review]

**Pull request merged**
